# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('dataset/Churn_Modelling.csv')
print(dataset.info())
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
None


In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)
print(X.shape)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
(10000, 10)


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)
print(X.shape)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
(10000, 12)


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=24, activation='relu'))

In [14]:
ann.add(tf.keras.layers.Dropout(0.1))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=24, activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 128, epochs = 500)

Epoch 1/500
63/63 [==============================] - 0s 1ms/step - loss: 0.6092 - accuracy: 0.7007
Epoch 2/500
63/63 [==============================] - 0s 1ms/step - loss: 0.4908 - accuracy: 0.7969
Epoch 3/500
63/63 [==============================] - 0s 1ms/step - loss: 0.4539 - accuracy: 0.7997
Epoch 4/500
63/63 [==============================] - 0s 1ms/step - loss: 0.4350 - accuracy: 0.8049
Epoch 5/500
63/63 [==============================] - 0s 1ms/step - loss: 0.4254 - accuracy: 0.8169
Epoch 6/500
63/63 [==============================] - 0s 1ms/step - loss: 0.4142 - accuracy: 0.8188
Epoch 7/500
63/63 [==============================] - 0s 1ms/step - loss: 0.4043 - accuracy: 0.8285
Epoch 8/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3972 - accuracy: 0.8341
Epoch 9/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3882 - accuracy: 0.8363
Epoch 10/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3782 - accuracy: 0.8431
Epoch 11/

63/63 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8655
Epoch 83/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3190 - accuracy: 0.8680
Epoch 84/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3204 - accuracy: 0.8681
Epoch 85/500
63/63 [==============================] - 0s 974us/step - loss: 0.3255 - accuracy: 0.8665
Epoch 86/500
63/63 [==============================] - 0s 911us/step - loss: 0.3229 - accuracy: 0.8665
Epoch 87/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3217 - accuracy: 0.8665
Epoch 88/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3229 - accuracy: 0.8680
Epoch 89/500
63/63 [==============================] - 0s 989us/step - loss: 0.3222 - accuracy: 0.8671
Epoch 90/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3203 - accuracy: 0.8700
Epoch 91/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3221 - accuracy: 0.8666
Epoch 9

63/63 [==============================] - 0s 1ms/step - loss: 0.3129 - accuracy: 0.8723
Epoch 164/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3152 - accuracy: 0.8710
Epoch 165/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3126 - accuracy: 0.8726
Epoch 166/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3144 - accuracy: 0.8702
Epoch 167/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3139 - accuracy: 0.8696
Epoch 168/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3148 - accuracy: 0.8702
Epoch 169/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3102 - accuracy: 0.8730
Epoch 170/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3122 - accuracy: 0.8745
Epoch 171/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3096 - accuracy: 0.8733
Epoch 172/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3148 - accuracy: 0.8704
Epoc

63/63 [==============================] - 0s 1ms/step - loss: 0.3087 - accuracy: 0.8745
Epoch 245/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3056 - accuracy: 0.8739
Epoch 246/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3038 - accuracy: 0.8754
Epoch 247/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3063 - accuracy: 0.8755
Epoch 248/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3012 - accuracy: 0.8739
Epoch 249/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3057 - accuracy: 0.8742
Epoch 250/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3048 - accuracy: 0.8724
Epoch 251/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3065 - accuracy: 0.8748
Epoch 252/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3059 - accuracy: 0.8744
Epoch 253/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3093 - accuracy: 0.8725
Epoc

63/63 [==============================] - 0s 1ms/step - loss: 0.3016 - accuracy: 0.8770
Epoch 326/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2991 - accuracy: 0.8764
Epoch 327/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2995 - accuracy: 0.8735
Epoch 328/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3013 - accuracy: 0.8730
Epoch 329/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2997 - accuracy: 0.8774
Epoch 330/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3009 - accuracy: 0.8765
Epoch 331/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3041 - accuracy: 0.8756
Epoch 332/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2990 - accuracy: 0.8739
Epoch 333/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3011 - accuracy: 0.8756
Epoch 334/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3023 - accuracy: 0.8745
Epoc

63/63 [==============================] - 0s 1ms/step - loss: 0.2974 - accuracy: 0.8774
Epoch 407/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2997 - accuracy: 0.8755
Epoch 408/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2953 - accuracy: 0.8781
Epoch 409/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3009 - accuracy: 0.8770
Epoch 410/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2978 - accuracy: 0.8731
Epoch 411/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2990 - accuracy: 0.8755
Epoch 412/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2967 - accuracy: 0.8769
Epoch 413/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2990 - accuracy: 0.8725
Epoch 414/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3004 - accuracy: 0.8749
Epoch 415/500
63/63 [==============================] - 0s 1ms/step - loss: 0.3002 - accuracy: 0.8744
Epoc

63/63 [==============================] - 0s 1ms/step - loss: 0.2954 - accuracy: 0.8758
Epoch 488/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2922 - accuracy: 0.8766
Epoch 489/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2975 - accuracy: 0.8765
Epoch 490/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2969 - accuracy: 0.8759
Epoch 491/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2974 - accuracy: 0.8765
Epoch 492/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2961 - accuracy: 0.8779
Epoch 493/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2932 - accuracy: 0.8801
Epoch 494/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2953 - accuracy: 0.8769
Epoch 495/500
63/63 [==============================] - 0s 990us/step - loss: 0.2956 - accuracy: 0.8780
Epoch 496/500
63/63 [==============================] - 0s 1ms/step - loss: 0.2972 - accuracy: 0.8771
Ep

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))

[[1488  107]
 [ 174  231]]
              precision    recall  f1-score   support

           0       0.90      0.93      0.91      1595
           1       0.68      0.57      0.62       405

    accuracy                           0.86      2000
   macro avg       0.79      0.75      0.77      2000
weighted avg       0.85      0.86      0.85      2000

